# Generated by Django 6.0.5 on 2026-07-31 16:15

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nickname", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", apps.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GeneVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chromosome", models.CharField(max_length=8)),
                ("position", models.BigIntegerField(null=True)),
                ("ref_allele", models.CharField(max_length=255)),
                ("alt_allele", models.CharField(max_length=255)),
                ("variation_type", models.CharField(blank=True, max_length=32)),
                ("dbsnp", models.CharField(blank=True, max_length=64)),
                ("gnomAD", models.CharField(blank=True, max_length=64)),
                (
                    "genes",
                    models.ManyToManyField(related_name="variants", to="core.gene"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneticReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_name", models.CharField(blank=True, max_length=120)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zygosity", models.CharField(blank=True, max_length=32)),
                ("category", models.FloatField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("reported_hgvs_c", models.CharField(blank=True, max_length=120)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.geneticreport",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.genevariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript_base",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                ("transcript_version", models.IntegerField(blank=True, null=True)),
                (
                    "hgvs_c",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, null=True
                    ),
                ),
                ("hgvs_p", models.CharField(blank=True, max_length=120)),
                ("exon", models.CharField(blank=True, max_length=32)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="core.genevariant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="genevariant",
            index=models.Index(fields=["dbsnp"], name="core_geneva_dbsnp_ee5ea8_idx"),
        ),
        migrations.AddIndex(
            model_name="genevariant",
            index=models.Index(
                fields=["chromosome", "position"], name="core_geneva_chromos_3e97f2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="genevariant",
            constraint=models.UniqueConstraint(
                fields=(
                    "chromosome",
                    "position",
                    "variation_type",
                    "ref_allele",
                    "alt_allele",
                ),
                name="unique_genomic_variant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientvariant",
            unique_together={("report", "variant")},
        ),
        migrations.AddIndex(
            model_name="transcriptannotation",
            index=models.Index(fields=["hgvs_c"], name="core_transc_hgvs_c_cf1159_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptannotation",
            index=models.Index(fields=["hgvs_p"], name="core_transc_hgvs_p_6fdd8d_idx"),
        ),
        migrations.AddConstraint(
            model_name="transcriptannotation",
            constraint=models.UniqueConstraint(
                fields=("variant", "hgvs_c"),
                name="unique_variant_transcript_annotation",
            ),
        ),
    ]
