# Generated by Django 6.0.5 on 2026-06-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chromosome", models.CharField(max_length=8)),
                ("position", models.BigIntegerField(null=True)),
                ("ref_allele", models.CharField(max_length=255)),
                ("alt_allele", models.CharField(max_length=255)),
                ("variation_type", models.CharField(blank=True, max_length=32)),
                ("dbsnp", models.CharField(blank=True, max_length=64)),
                ("gnomAD", models.CharField(blank=True, max_length=64)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinVarGeneVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinvar_id", models.CharField(max_length=64)),
                ("clinvar_url", models.URLField(blank=True, max_length=300)),
                ("clinvar_category", models.CharField(blank=True, max_length=80)),
                (
                    "gene_variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinvar_entry",
                        to="core.genevariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneticReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_name", models.CharField(blank=True, max_length=120)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zygosity", models.CharField(blank=True, max_length=32)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("comment", models.TextField(blank=True)),
                ("reported_hgvs_c", models.CharField(blank=True, max_length=120)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.geneticreport",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.genevariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript_base", models.CharField(db_index=True, max_length=32)),
                ("transcript_version", models.IntegerField(blank=True, null=True)),
                ("hgvs_c", models.CharField(db_index=True, max_length=120)),
                ("hgvs_p", models.CharField(blank=True, max_length=120)),
                ("exon", models.CharField(blank=True, max_length=32)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="core.genevariant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="genevariant",
            constraint=models.UniqueConstraint(
                fields=("chromosome", "position", "ref_allele", "alt_allele"),
                name="unique_genomic_variant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientvariant",
            unique_together={("report", "variant")},
        ),
        migrations.AddConstraint(
            model_name="transcriptannotation",
            constraint=models.UniqueConstraint(
                fields=("variant", "hgvs_c"),
                name="unique_variant_transcript_annotation",
            ),
        ),
    ]
