# Generated by Django on 2026-06-01

from django.db import migrations, models


def forward_backfill_variant_links(apps, schema_editor):
    GeneVariant = apps.get_model("core", "GeneVariant")
    HGVS = apps.get_model("core", "HGVS")

    for variant in GeneVariant.objects.all().iterator():
        if variant.gene_id:
            variant.genes.add(variant.gene_id)

        if variant.hgvs_c or variant.hgvs_p:
            hgvs_entry, _ = HGVS.objects.get_or_create(
                hgvs_c=variant.hgvs_c or "",
                hgvs_p=variant.hgvs_p or "",
                mane_select=False,
            )
            variant.hgvs_entries.add(hgvs_entry)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HGVS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hgvs_c", models.CharField(blank=True, max_length=120)),
                ("hgvs_p", models.CharField(blank=True, max_length=120)),
                ("mane_select", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hgvs_c", "hgvs_p", "mane_select"),
                        name="unique_hgvs_entry",
                    )
                ]
            },
        ),
        migrations.AddField(
            model_name="genevariant",
            name="genes",
            field=models.ManyToManyField(related_name="variants", to="core.gene"),
        ),
        migrations.AddField(
            model_name="genevariant",
            name="hgvs_entries",
            field=models.ManyToManyField(related_name="variants", to="core.hgvs"),
        ),
        migrations.RunPython(forward_backfill_variant_links, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="genevariant",
            name="unique_genomic_variant",
        ),
        migrations.RemoveField(
            model_name="genevariant",
            name="gene",
        ),
        migrations.RemoveField(
            model_name="genevariant",
            name="hgvs_c",
        ),
        migrations.RemoveField(
            model_name="genevariant",
            name="hgvs_p",
        ),
        migrations.AddConstraint(
            model_name="genevariant",
            constraint=models.UniqueConstraint(
                fields=("chromosome", "position", "variation_type", "dbsnp"),
                name="unique_genomic_variant",
            ),
        ),
    ]
