# Generated by Django 6.0.5 on 2026-07-31 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_joined",
            new_name="date_created",
        ),
    ]
