# Generated by Django 6.0.5 on 2026-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcriptannotation",
            name="hgvs_c",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, null=True
            ),
        ),
    ]
