# Generated by Django 6.0.5 on 2026-06-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_variant_m2m_hgvs"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="genevariant",
            name="unique_genomic_variant",
        ),
        migrations.RemoveConstraint(
            model_name="hgvs",
            name="unique_hgvs_entry",
        ),
        migrations.AddField(
            model_name="genevariant",
            name="alt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genevariant",
            name="ref",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hgvs",
            name="variant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hgvs",
                to="core.genevariant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hgvs",
            name="hgvs_c",
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="hgvs",
            name="hgvs_p",
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name="genevariant",
            constraint=models.UniqueConstraint(
                fields=("chromosome", "position", "variation_type", "ref", "alt"),
                name="unique_genomic_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="hgvs",
            constraint=models.UniqueConstraint(
                fields=("hgvs_c", "hgvs_p"), name="unique_hgvs_entry"
            ),
        ),
        migrations.RemoveField(
            model_name="genevariant",
            name="hgvs_entries",
        ),
        migrations.RemoveField(
            model_name="hgvs",
            name="mane_select",
        ),
    ]
