# Generated by Django 6.0.5 on 2026-07-31 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_date_joined_user_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="nickname",
            new_name="username",
        ),
    ]
