# Generated by Django 6.0.5 on 2026-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_patientvariant_category"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="genevariant",
            index=models.Index(fields=["dbsnp"], name="core_geneva_dbsnp_ee5ea8_idx"),
        ),
        migrations.AddIndex(
            model_name="genevariant",
            index=models.Index(
                fields=["chromosome", "position"], name="core_geneva_chromos_3e97f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptannotation",
            index=models.Index(fields=["hgvs_c"], name="core_transc_hgvs_c_cf1159_idx"),
        ),
        migrations.AddIndex(
            model_name="transcriptannotation",
            index=models.Index(fields=["hgvs_p"], name="core_transc_hgvs_p_6fdd8d_idx"),
        ),
    ]
