# Generated by Django 6.0.5 on 2026-06-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_transcriptannotation_transcript_base"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="genevariant",
            name="unique_genomic_variant",
        ),
        migrations.AddConstraint(
            model_name="genevariant",
            constraint=models.UniqueConstraint(
                fields=("gene", "chromosome", "position", "ref_allele", "alt_allele"),
                name="unique_genomic_variant",
            ),
        ),
    ]
