# Generated by Django 6.0.5 on 2026-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_genevariant_unique_genomic_variant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hgvs",
            name="hgvs_c",
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="hgvs",
            name="hgvs_p",
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
