# Generated by Django 6.0.5 on 2026-07-31 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_nickname_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="geneticreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="genetic_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
