# Generated by Django 6.0.5 on 2026-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinVarGeneVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinvar_id", models.CharField(max_length=64)),
                ("clinvar_classification", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
