# Generated by Django 6.0.5 on 2026-06-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_remove_genevariant_unique_genomic_variant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinVarAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinvar_variation_id", models.IntegerField()),
                ("accession", models.CharField(max_length=32)),
                ("classification", models.CharField(max_length=64)),
                ("review_status", models.CharField(max_length=128)),
                ("disease", models.CharField(max_length=256)),
                ("hgvs", models.TextField()),
                ("last_updated", models.DateField()),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinvar_annotation",
                        to="core.genevariant",
                    ),
                ),
            ],
        ),
    ]
