# Generated by Django 6.0.5 on 2026-06-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinVarGeneVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinvar_id", models.CharField(max_length=64)),
                ("clinvar_url", models.URLField(blank=True, max_length=300)),
                ("clinvar_category", models.CharField(blank=True, max_length=80)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "gene_variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinvar_entry",
                        to="core.genevariant",
                    ),
                ),
            ],
        ),
    ]
