# Generated by Django 6.0.5 on 2026-07-31 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinvar", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinvargenevariant",
            name="gene_variant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinvar_entry",
                to="core.genevariant",
            ),
        ),
    ]
