# Generated by Django 6.0.5 on 2026-06-16 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinvar", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinvargenevariant",
            old_name="clinvar_category",
            new_name="clinvar_classification",
        ),
    ]
