# Generated by Django 6.0.5 on 2026-06-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "clinvar",
            "0002_rename_clinvar_category_clinvargenevariant_clinvar_classification",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinvargenevariant",
            name="clinvar_url",
        ),
        migrations.AlterField(
            model_name="clinvargenevariant",
            name="clinvar_classification",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
